---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: {{ .Values.namespace }}
  labels:
    name: catalogue
spec:
  selector:
    app: catalogue
  type: {{ .Values.catalogue.service.type }}
  ports:
    - name: catalogue
      protocol: TCP
      port: 80
      targetPort: {{ .Values.catalogue.containerPort }}
      {{- if eq .Values.catalogue.service.type "NodePort" }}
      nodePort: {{ .Values.catalogue.service.nodePort }}
      {{- end }}
  selector:
    name: catalogue
