apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "ingress-sock-shop"
    # Ingress Core Settings
    alb.ingress.kubernetes.io/group.name: my-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/security-groups:
{{- if not .Values.ssl.enabled }}
    # SSL Settings
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
{{- else }}
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    #Important Note:  Need to add health check path annotations in service level if we are planning to use multiple targets in a load balancer    
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'   
    # alb.ingress.kubernetes.io/auth-session-cookie: sock-shop-cookie
    # alb.ingress.kubernetes.io/auth-session-timeout: '86400'
    # SSL Settings
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443},{"HTTP": 80}]'
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-3:501984417376:certificate/e51da241-e6f8-48e3-963c-cd6d96b328f0
    # alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01 #Optional (Picks default if not used)
    # SSL Redirect Setting
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # External DNS - For creating a Record Set in Route53
    # external-dns.alpha.kubernetes.io/hostname: sock-shop.maikimike.me
    cert-manager.io/cluster-issuer: 'letsencrypt-staging' 
    certmanager.k8s.io/acme-challenge-type: http01    
{{- end }}
  labels:
{{ toYaml .Values.ingress.labels | indent 4 }}
  name: {{ template "fullname" .}}-socks-ingress
spec:
  ingressClassName: my-aws-ingress-class # Ingress Class
# {{- if .Values.ssl.enabled }}
#   tls:
#   - hosts:
#     - "*.maikimike.me"
# {{- end }}
  rules:
  # - host: {{ .Values.baseDomain }} 
  #   http: 
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
# {{- if .Values.ssl.enabled }}
#       host: sock-shop.{{ .Values.baseDomain }}
# {{- end }}
